sonar.projectKey=kirillchistov_fullstack-javascript-project-46
sonar.organization=kirillchistov
sonar.sources=src,bin
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=coverage/**,node_modules/**
sonar.sourceEncoding=UTF-8

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=fullstack-javascript-project-46
#sonar.projectVersion=1.0



